import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getGlobalPageData } from "@/data/loaders";
import { Header } from "@/components/custom/header";
import { Footer } from "@/components/custom/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalPageData();
  console.log("footer", globalData.footer);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header data={globalData.header} />
        <div className="">{children}</div>
        <Footer data={globalData.footer} />
      </body>
    </html>
  );
}
